### ISSUE TITLE
ERROR in Metadata version mismatch

### ISSUE THREAD

**Issue by gangfang** [cipchk/ngx-filesaver#1]
Hi, thanks for the package.

Got an error when building the project saying:

> ERROR in Metadata version mismatch for module /Users/gang_fang/Desktop/CMSA-frontend/node_modules/ngx-filesaver/index.d.ts, found version 4, expected 3

Fixed by changing version 34 to 3 in all *.metadata.json file within ngx-filesaver directory.

**Comment by cipchk** [comment]
You can using `0.0.2` version in angular4 else `1.0.0`.
