### ISSUE TITLE
Does not work on Apple device

### ISSUE THREAD

**Issue by snahmad** [cipchk/ngx-filesaver#11]
I tried on safari.

it cannot download file on Apple devices.

Any idea?

**Comment by cipchk** [comment]
[Supported Browsers](https://github.com/eligrey/FileSaver.js/#supported-browsers)

- [Related discussion](https://github.com/eligrey/FileSaver.js/issues/375)

**Comment by snahmad** [comment]
not good enough for my use case. I just want to check if I am running any apple device. I need to make my download and other buttons hidden. How can I check If I am on apple device using angular 2x?

**Comment by cipchk** [comment]
Feature detection is possible:


```ts
try {
    var isFileSaverSupported = !!new Blob;
} catch (e) {}
```

If this a valid solution, i will try to integrate it.
