### ISSUE TITLE
saving file on firefox

### ISSUE THREAD

**Issue by snahmad** [cipchk/ngx-filesaver#13]
It prompt for file dialog open/save.

how we can avoid it.

**Comment by cipchk** [comment]
@snahmad Don't understand what you mean, shouldn't there be a dialog for saving?

**Comment by snahmad** [comment]
It is Firefox browser behavior when save file. It pop dialog with option to open or save file.

I am downloading multiple file one by one. It is prompting for each file.
I thought there must be way to tell Firefox. don't ask /prompt for each file.

**Comment by cipchk** [comment]
Can't.

May be you can package all file to single zip file.

**Comment by snahmad** [comment]
ok.
