### ISSUE TITLE
"save" does not have option to set "disableAutoBOM" flag.

### ISSUE THREAD

**Issue by himanshujain1985** [cipchk/ngx-filesaver#14]
"save" does not have the option to set "disableAutoBOM" flag.

The saveAs function of the fileSaver library has a disableAutoBOM flag, which is default to false. I need to set this flag to true. However, this library does not have this option.

Request to add this feature.

**Comment by himanshujain1985** [comment]
Any update on this issue? Its been a long time since this is requested.

**Comment by cipchk** [comment]
@himanshujain1985 I'm sorry, i forget this issues. i will slove it right away.

**Comment by himanshujain1985** [comment]
Thanks @cipchk.
