### ISSUE TITLE
'/ɵɵdefineInjectable' in dist

### ISSUE THREAD

**Issue by JacopoSciampi** [cipchk/ngx-filesaver#16]
I've followed the guide and this message occurs : 

./node_modules/ngx-filesaver/fesm5/ngx-filesaver.js 54:39-57
"export 'ɵɵdefineInjectable' was not found in '@angular/core'.

**Comment by robertoost** [comment]
Same thing happened to me.
It only shows as a warning in the console when compiling the project, but it breaks the project after I serve it.

**Comment by cipchk** [comment]
@JacopoSciampi @robertoost 

the `8.x` version only support angular8, pls refer to [abort `defineInjectable` description](https://github.com/angular/angular/issues/30413#issuecomment-491531239). 

you can tring `2.x` version.
