### ISSUE TITLE
导出docx,pdf，打开文件出错

### ISSUE THREAD

**Issue by JiongChung** [cipchk/ngx-filesaver#18]
按示例，将方法第二个参数，true改成flase时，onDown('docx', false)"
导出的docx,pdf打开文件出错

**Comment by cipchk** [comment]
肯定会出错，因为示例中并没有在本地真正的生成一个有效的 docx 或 pdf 格式的文件，`ngx-filesaver` 重点在于保存而非文件产生，若需要本地生成 pdf 你需要借助第三方，例如：[jsPDF 
](https://github.com/MrRio/jsPDF)
