### ISSUE TITLE
instead of downloading i want to save data in local file  

### ISSUE THREAD

**Issue by ArpithaGMGowda** [cipchk/ngx-filesaver#20]
Hi  

instead of downloading a file i want to save the data in local file and it should append the previous text/data in angular 7.
any solution ??

Thank you in advance

**Comment by cipchk** [comment]
You can using `Blob` build, instantiate the `Blob` object and pass a text string as the first parameter and blob type as the second parameter.

```ts
const blob = new Blob(["Welcome to Websparrow.org."], { type: "text/plain;charset=utf-8" });

FileSaverService.save(blob);
```
