### ISSUE TITLE
 isFileSaverSupported() An accessor cannot be declared in an ambient context.

### ISSUE THREAD

**Issue by hennychen** [cipchk/ngx-filesaver#23]
ERROR in ../node_modules/ngx-filesaver/src/filesaver.service.d.ts:3:9 - error TS1086: An accessor cannot be declared in an ambient context.

3     get isFileSaverSupported(): boolean;

**Comment by cipchk** [comment]
@hennychen Pls upgrade typescript to `~3.8.x`.

**Comment by f1nch** [comment]
Unfortunately in my case I am unable to update typescript version. Is there any other solution or is it possible to support older versions of typescript?

**Comment by cipchk** [comment]
@f1nch try using `8.1.0` version

**Comment by f1nch** [comment]
@cipchk `8.1.0` works, thanks!

**Comment by hiteshtare** [comment]
Still the same error is encountered:
`ERROR in node_modules/ngx-filesaver/src/filesaver.service.d.ts(3,9): error TS1086: An accessor cannot be declared in an ambient context.`
for package.json

> {
>   "name": "io-dna-angular",
>   "version": "0.0.0",
>   "scripts": {
>     "ng": "ng",
>     "start": "ng serve --port 4400",
>     "watch": "ng serve -o --port 4400",
>     "build": "ng build --configuration=production",
>     "test": "ng test",
>     "lint": "ng lint",
>     "e2e": "ng e2e"
>   },
>   "private": true,
>   "dependencies": {
>     "@angular/animations": "^7.1.4",
>     "@angular/common": "~7.1.0",
>     "@angular/compiler": "~7.1.0",
>     "@angular/core": "~7.1.0",
>     "@angular/forms": "~7.1.0",
>     "@angular/http": "^7.1.4",
>     "@angular/platform-browser": "~7.1.0",
>     "@angular/platform-browser-dynamic": "~7.1.0",
>     "@angular/router": "~7.1.0",
>     "@markpieszak/ng-application-insights": "^7.0.1",
>     "@ng-bootstrap/ng-bootstrap": "^4.0.1",
>     "@ng-idle/keepalive": "^6.0.0-beta.3",
>     "@types/ldclient-js": "^1.1.11",
>     "adal-angular": "^1.0.17",
>     "adal-angular4": "^4.0.9",
>     "angular-datatables": "^7.0.0",
>     "angular-progress-http": "^1.0.0",
>     "angular-svg-icon": "^7.2.1",
>     "core-js": "^2.5.4",
>     "datatables.net": "^1.10.19",
>     "datatables.net-buttons-dt": "^1.5.6",
>     "datatables.net-dt": "^1.10.19",
>     "expose-loader": "^0.7.5",
>     "file-saver": "^2.0.2",
>     "jquery": "^3.3.1",
>     "ldclient-js": "^2.10.2",
>     "moment": "^2.24.0",
>     "ng-bullet": "^1.0.3",
>     "ng-sidebar": "^8.0.0",
>     "ngx-filesaver": "^9.0.0",
>     "ngx-logger": "^3.3.13",
>     "ngx-moment": "^3.3.0",
>     "ngx-spinner": "^6.1.2",
>     "ngx-toastr": "^9.1.2",
>     "powerbi-client": "^2.7.1",
>     "rxjs-compat": "^6.3.3",
>     "tslib": "^1.9.0",
>     "zone.js": "~0.8.26"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.11.0",
>     "@angular/cli": "~7.1.1",
>     "@angular/compiler-cli": "~7.1.0",
>     "@angular/language-service": "~7.1.0",
>     "@types/adal": "^1.0.29",
>     "@types/datatables.net": "^1.10.15",
>     "@types/jasmine": "~2.8.8",
>     "@types/jasminewd2": "~2.0.3",
>     "@types/jquery": "^3.3.29",
>     "@types/node": "~8.9.4",
>     "codelyzer": "~4.5.0",
>     "fs-extra": "^8.0.1",
>     "git-describe": "^4.0.4",
>     "jasmine-core": "~2.99.1",
>     "jasmine-spec-reporter": "~4.2.1",
>     "karma": "~3.1.1",
>     "karma-chrome-launcher": "~2.2.0",
>     "karma-coverage-istanbul-reporter": "~2.0.1",
>     "karma-jasmine": "~1.1.2",
>     "karma-jasmine-html-reporter": "^0.2.2",
>     "karma-parallel": "^0.3.1",
>     "node-sass": "^4.12.0",
>     "protractor": "~5.4.0",
>     "ts-node": "~7.0.0",
>     "tslint": "~5.11.0",
>     "typescript": "~3.1.6"
>   }
> }
>

**Comment by ganeshchukka** [comment]
Still the same error is encountered . tell me how to use this for angular 6 ?
