### ISSUE TITLE
warning following Angular 10 update

### ISSUE THREAD

**Issue by gpsimmo** [cipchk/ngx-filesaver#24]
Following the recent Angular 10 update.

`ng serve` now produces the following warning:

> WARNING in node_modules/ngx-filesaver/__ivy_ngcc__/fesm2015/ngx-filesaver.js depends on file-saver. CommonJS or AMD dependencies can cause optimization bailouts.
> For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by cipchk** [comment]
https://github.com/cipchk/ngx-filesaver/tree/dev-ng10#configuring-commonjs-dependencies

**Comment by Leccho** [comment]
Thanks for the update!

**Comment by SBahre** [comment]
I am still getting this warning with 
angular v16, 
ngx-filesaver v17.0.0, 
file-saver: v2.0.5

Please suggest the solution.

**Comment by cipchk** [comment]
@SBahre If you are using angular 16, please use version 16.x.
