### ISSUE TITLE
Downloaded rar file has very small size

### ISSUE THREAD

**Issue by aviralgoyal** [cipchk/ngx-filesaver#26]
When downloading a file using file-saver package the file is getting downloaded correctly with size 600kb 
with this code :
`saveAs(fileUrl, fileName);`

But when I'm using ngx-filesaver the file dowloaded is 65kb and the unrar process is giving an errror
this._FileSaverService.save(fileUrl, fileName);

Any idea what I might be doing wrong? or is it some bug?

The file I'm using is a rar file which is being served by a nginx server upon calling the fileUrl.

**Comment by cipchk** [comment]
Can you provide the download address of rar?

**Comment by aviralgoyal** [comment]
Can i send it to you as private message?

**Comment by aviralgoyal** [comment]
https://images.aurigasoftware.in/1/sampling/sam-1595998137093.rar

**Comment by aviralgoyal** [comment]
rartest.aurigasoftware.in/1/sampling/sam-1596067683714.zip

**Comment by cipchk** [comment]
Due to the limitation of cors, I can't reproduce it according to your URL. 

But this file can be downloaded normally in my environment:

![image](https://user-images.githubusercontent.com/2987467/88874398-94de4500-d251-11ea-879e-824e620313df.png)

Are there any details about this errror?

**Comment by aviralgoyal** [comment]
It seems the issue as you pointed out might be CORS related as I'm directly serving the file from nginx which has a default policy of lax. I'm going to create a backend server for handling such requests and send the data as BLOB to eliminate this problem completely.

Thanks a lot for your prompt replies, much appreciated. 
Stay Safe!
