### ISSUE TITLE
Update to Angular 13/14 with Ivy instead of View Engine

### ISSUE THREAD

**Issue by YanerTavuz** [cipchk/ngx-filesaver#32]
When building our project with ngx-filesaver the build warns about the library still using View Engine

**Comment by cipchk** [comment]
I make sure use lvy compliter mode of version `13`, Can you provider build log and `ngx-filesaver` version of `package.json`?

**Comment by YanerTavuz** [comment]
Hi! 
We are using the package ngx-lightbox@2.6.1 which uses ngx-filesaver@8.1.0

I have created an issue with ngx-lightbox as well.

The only thing we get in our build is this 
![image](https://user-images.githubusercontent.com/48799772/171394955-d8b91913-2a0d-4e03-86ef-037e7af5b247.png)

**Comment by cipchk** [comment]
You can try only upgrade `ngx-filesaver` to `13.x`, If you local `@angular/core` is `13.x` (or other `@angular/core` version). like this:

```bash
yarn add ngx-filesaver@13
```

**Comment by YanerTavuz** [comment]
You are absolutely right, the issue is not your package. It is the other package ngx-lightbox. I am closing this issue, sorry for the inconvenience
