### ISSUE TITLE
Bump to ngx-filesaver 15.0.1 results in Errors

### ISSUE THREAD

**Issue by TheCell** [cipchk/ngx-filesaver#42]
We are using this package in our Angular 15 application and during a regular maintenance task we updated the package from 15.0.0 to  15.0.1. However, the version bump results in errors:
![image](https://user-images.githubusercontent.com/3481579/232825061-c98592c0-0f53-4838-8e6f-b4820038c907.png)
```javascript
Error: export 'takeUntil' (imported as 'takeUntil') was not found in 'rxjs' (possible exports: Ar
gumentOutOfRangeError, AsyncSubject, BehaviorSubject, ConnectableObservable, EMPTY, EmptyError, GroupedObservable, NEVER, Notification, NotificationKind, ObjectUnsub
scribedError, Observable, ReplaySubject, Scheduler, Subject, Subscriber, Subscription, TimeoutError, UnsubscriptionError, VirtualAction, VirtualTimeScheduler, animat
ionFrame, animationFrameScheduler, asap, asapScheduler, async, asyncScheduler, bindCallback, bindNodeCallback, combineLatest, concat, config, defer, empty, forkJoin,
 from, fromEvent, fromEventPattern, generate, identity, iif, interval, isObservable, merge, never, noop, observable, of, onErrorResumeNext, pairs, partition, pipe, q
ueue, queueScheduler, race, range, scheduled, throwError, timer, using, zip)
```

I suspect it has to do with this commit b2978bd86bac9f8249fbbc12525de06916612f3a.

I tried to setup a new angular project, import ngx-filesaver 15.0.1 and rxjs takeuntil directly but it does not result in the error on its own.
But If I manually set the rxjs version of the project to ^6.6.7
```javascript
"rxjs": "^6.6.7",
```
and then using the older import for rxjs in my component, it will fail with the same error message.

```Typescript
import { Component } from '@angular/core';
import { FileSaverService } from 'ngx-filesaver';
import { fromEvent, interval } from 'rxjs';
import { takeUntil } from 'rxjs/operators';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-tour-of-heroes';

  public constructor (private _FileSaverService: FileSaverService)
  {
    console.log(_FileSaverService);

    const source = interval(1000);
    const clicks = fromEvent(document, 'click');
    const result = source.pipe(takeUntil(clicks));
    result.subscribe(x => console.log(x));
  }
}
```

Is the newly added imports to `lib/src/filesaver.directive.ts` a breaking change?
In version 6.6.7 the 'takeUntil' was still imported like this: `import { takeUntil } from 'rxjs/operators';` (which we imported from there)
Might be helpful.

**Comment by cipchk** [comment]
The main version number of ngx-filesave has always been consistent with that of angular.

Starting from angular 15.0, the rxjs version has been updated to 7.8.

And rxjs has beed deprecated 'rxjs/operators' since [7.2](https://rxjs.dev/guide/importing#new-in-rxjs-v720). The above are some historical factors, and it is reasonable to use 'rxjs' instead of 'rxjs/operators'.

**Comment by TheCell** [comment]
Thank you very much for your answer. I think this issue can be closed, it's a mistake on our part to not have upgraded rxjs when upgrading Angular until now!
