### ISSUE TITLE
上传后可以下载，过一会就不行了

### ISSUE THREAD

**Issue by EnochGao** [cipchk/ngx-filesaver#5]
我按照你的方法angular4不兼容性就把文件复制进来，调用下载文件的地址是阿里云oss存的，但是我上传后可以下载，过一会就报错了，请问这是什么原因，代码`  // 保存图片到本地
  saveImageToLocal(image: any, fromRemote: boolean) {
    const fileName = `图片`;
    this.log.debug('show URL', image.imageUrl);
    if (fromRemote) {
      this._httpClient.get(`${image.imageUrl}`, {
        observe: 'response',
        responseType: 'blob'
      }).subscribe(res => {
        this.log.debug('show res:', res);
        this._FileSaverService.save(res.body, fileName);
      });
      return;
    }
  }`
报的错误`Access to XMLHttpRequest at 'http://vehicles-data-center.oss-cn-hangzhou.aliyuncs.com/%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B.png' from origin 'http://localhost:57767' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. `

**Comment by cipchk** [comment]
跨域了，请自行百度，不过一般没有这么干的吧，都是先通过自己的服务器再转阿里云的吧。

**Comment by EnochGao** [comment]
是前端直接上传到阿里云，阿里云返回的地址存到了数据库，下载图片地址是从数据库读的，搜了一下知道是可能是跨域问题，跨域问题是要在oss里设置原因还是我本地代码的问题这点没有搞清楚
