### ISSUE TITLE
file-saver not installed automatically as dependency

### ISSUE THREAD

**Issue by bpeynet** [cipchk/ngx-filesaver#7]
When ngx-filesaver is installed, the package **file-saver** is not installed.
As mentioned by the documentation, it is necessary to execute `npm i file-saver` as well.
Could `package.json` be changed so that the necessary package **file-saver** is installed automatically ?
Adding the package as a dependency could do, I think. For now, there is only tslib :
![image](https://user-images.githubusercontent.com/16057058/50377326-a6924c00-061b-11e9-88a2-73c0478204ed.png)

**Comment by cipchk** [comment]
@bpeynet  Many projects still depend on 1.x version of file-saver, so installation dependencies it to the user to choose, pls refer [Installation](https://github.com/cipchk/ngx-filesaver#installation).
